# Generated by Django 5.0.1 on 2024-02-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sms_carrier',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sms_type',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='term_location',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voice_carrier',
            name='record_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
