# Generated by Django 4.2.7 on 2024-02-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0007_remove_did_type_remove_did_error_type_and_more'),
        ('assist_dids', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Type',
        ),
    ]
