# Generated by Django 5.0.1 on 2024-02-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0001_initial'),
        ('dids', '0004_alter_did_did_uuid_alter_did_sms_carrier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS_Carrier',
        ),
    ]
