# Generated by Django 5.0.1 on 2024-02-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0002_alter_service_record_id_alter_sms_carrier_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
