# Generated by Django 5.0.1 on 2024-02-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0002_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sms_carrier',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sms_type',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term_location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='term_location',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voice_carrier',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
