# Generated by Django 5.0.1 on 2024-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0003_service_is_synced_sms_carrier_is_synced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('record_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
        ),
    ]
