# Generated by Django 4.2.7 on 2024-02-15 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assist_dids', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Did_Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('reseller', models.CharField(blank=True, max_length=200, null=True)),
                ('in_method', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('change_date', models.CharField(blank=True, max_length=10, null=True)),
                ('voice_carrier', models.CharField(blank=True, max_length=30, null=True)),
                ('sms_enabled', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_carrier', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_type', models.CharField(blank=True, max_length=30, null=True)),
                ('sms_campaign', models.CharField(blank=True, max_length=30, null=True)),
                ('term_location', models.CharField(blank=True, max_length=30, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('extension', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('onboard_date', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('e911_enabled_billed', models.CharField(blank=True, max_length=10, null=True)),
                ('e911_cid', models.CharField(blank=True, null=True)),
                ('e911_address', models.CharField(blank=True, max_length=150, null=True)),
                ('did_uuid', models.CharField(max_length=50, unique=True)),
                ('service_1', models.CharField(blank=True, max_length=100, null=True)),
                ('service_2', models.CharField(blank=True, max_length=100, null=True)),
                ('service_3', models.CharField(blank=True, max_length=100, null=True)),
                ('service_4', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date_time', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Did',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('in_method', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('change_date', models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y')),
                ('sms_enabled', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('sms_campaign', models.CharField(blank=True, max_length=20, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('extension', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('onboard_date', models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('e911_enabled_billed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('e911_cid', models.BigIntegerField(blank=True, null=True)),
                ('e911_address', models.TextField(blank=True, max_length=150, null=True)),
                ('did_uuid', models.UUIDField(default=uuid.UUID('34bea547-cc32-4d3a-b1d1-a0166f90469d'), unique=True)),
                ('service_1', models.TextField(blank=True, max_length=100, null=True)),
                ('service_2', models.TextField(blank=True, max_length=100, null=True)),
                ('service_3', models.TextField(blank=True, max_length=100, null=True)),
                ('service_4', models.TextField(blank=True, max_length=100, null=True)),
                ('updated_date_time', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='%m/%d/%Y %H:%M:%S')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_dids', to='customers.customer')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_dids', to='customers.customer')),
                ('sms_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.sms_carrier')),
                ('sms_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.sms_type')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.status')),
                ('term_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.term_location')),
                ('voice_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.voice_carrier')),
            ],
        ),
    ]
