# Generated by Django 5.0.1 on 2024-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Did',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_uuid', models.TextField(max_length=50)),
                ('did', models.SmallIntegerField(max_length=10)),
                ('in_method', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('voice_carrier', models.CharField(choices=[('IW', 'INTQ - Wholesale'), ('IO', 'INTQ - OC'), ('TWI', 'Twilio')], max_length=3, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('change_date', models.DateField(null=True, verbose_name='%m/%d/%Y')),
                ('type', models.CharField(choices=[('F', 'Fusion'), ('T', 'Teams'), ('HS', 'Hosted SMS'), ('PK', 'Parked'), ('IV', 'Inventory'), ('EF', 'Efax'), ('OP', 'Orphaned'), ('CL', 'Comelit')], max_length=2, null=True)),
                ('sms_enabled', models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('sms_carrier', models.CharField(choices=[('INTQ', 'Intelligent Q Network'), ('TWL', 'Twilio')], max_length=4, null=True)),
                ('sms_type', models.CharField(choices=[('YP', 'Yak Personal'), ('YS', 'Yak Shared'), ('YB', 'Yak Personal and Shared'), ('IA', 'INTQ API'), ('CL', 'Clerk'), ('SI', 'SIP/Simple')], max_length=2, null=True)),
                ('sms_campaign', models.CharField(max_length=20, null=True)),
                ('term_location', models.CharField(choices=[('SE', 'SBC East'), ('SW', 'SBC West'), ('HE', 'Hosted East'), ('HW', 'Hosted West'), ('OC', 'Operator Connect')], max_length=2, null=True)),
                ('customer', models.CharField(max_length=30, null=True)),
                ('reseller_msp', models.CharField(max_length=30, null=True)),
                ('user_first_name', models.CharField(max_length=30, null=True)),
                ('user_last_name', models.CharField(max_length=30, null=True)),
                ('extension', models.SmallIntegerField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('onboard_date', models.DateField(null=True, verbose_name='%m/%d/%Y')),
                ('note', models.TextField(max_length=255, null=True)),
                ('e911_enabled_billed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True)),
                ('e911_cid', models.SmallIntegerField(max_length=10, null=True)),
                ('e911_address', models.TextField(max_length=150, null=True)),
                ('service_1', models.TextField(max_length=100, null=True)),
                ('service_2', models.TextField(max_length=100, null=True)),
                ('service_3', models.TextField(max_length=100, null=True)),
                ('service_4', models.TextField(max_length=100, null=True)),
                ('update_date_time', models.DateField(null=True, verbose_name='%m/%d/%Y %H:%M:%S')),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
