# Generated by Django 5.0.1 on 2024-01-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='did',
            name='reseller_msp',
        ),
        migrations.RemoveField(
            model_name='did',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='did',
            name='update_date_time',
        ),
        migrations.AddField(
            model_name='did',
            name='reseller',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='did',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='did',
            name='updated_date_time',
            field=models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='did',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y'),
        ),
        migrations.AlterField(
            model_name='did',
            name='customer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='e911_address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='e911_cid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='e911_enabled_billed',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='extension',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='in_method',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='onboard_date',
            field=models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y'),
        ),
        migrations.AlterField(
            model_name='did',
            name='service_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='service_2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='service_3',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='service_4',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_carrier',
            field=models.CharField(blank=True, choices=[('INTQ', 'INTQ'), ('TWL', 'Twilio')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_enabled',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('YP', 'Yak Personal'), ('YS', 'Yak Shared'), ('YB', 'Yak Personal and Shared'), ('IA', 'INTQ API'), ('CL', 'Clerk'), ('SI', 'SIP/Simple')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Disco')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='term_location',
            field=models.CharField(blank=True, choices=[('SE', 'SBC - East'), ('SW', 'SBC - West'), ('HE', 'Hosted - East'), ('HW', 'Hosted - West'), ('OC', 'OP - Operator Connect')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='type',
            field=models.CharField(blank=True, choices=[('F', 'Fusion'), ('T', 'Teams'), ('HS', 'Hosted SMS'), ('PK', 'Parked'), ('IV', 'Inventory'), ('EF', 'Efax'), ('OP', 'Orphaned'), ('CL', 'Comelit')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='voice_carrier',
            field=models.CharField(blank=True, choices=[('IW', 'INTQ - Wholesale'), ('IO', 'INTQ - OC'), ('TWI', 'Twilio')], max_length=3, null=True),
        ),
    ]
