# Generated by Django 5.0.1 on 2024-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='did',
            name='e911_cid',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='extension',
            field=models.SmallIntegerField(null=True),
        ),
    ]
