# Generated by Django 4.2.7 on 2024-02-01 20:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='updated_date_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
    ]
