# Generated by Django 4.2.7 on 2024-02-02 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('6413132b-c666-4602-981d-116b252c663f'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='e911_enabled_billed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='in_method',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_carrier',
            field=models.CharField(blank=True, choices=[('INTQ', 'INTQ'), ('Twilio', 'Twilio')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_enabled',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('Yak Personal', 'Yak Personal'), ('Yak Shared', 'Yak Shared'), ('Yak Personal and Shared', 'Yak Personal and Shared'), ('INTQ API', 'INTQ API'), ('Clerk', 'Clerk'), ('SIP/Simple', 'SIP/Simple')], max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disco', 'Disco')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='term_location',
            field=models.CharField(blank=True, choices=[('SBC - East', 'SBC - East'), ('SW', 'SBC - West'), ('Hosted - East', 'Hosted - East'), ('Hosted - West', 'Hosted - West'), ('OP - Operator Connect', 'OP - Operator Connect')], max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='type',
            field=models.CharField(blank=True, choices=[('Fusion', 'Fusion'), ('Teams', 'Teams'), ('Hosted SMS', 'Hosted SMS'), ('Parked', 'Parked'), ('Inventory', 'Inventory'), ('Efax', 'Efax'), ('Orphaned', 'Orphaned'), ('Comelit', 'Comelit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='voice_carrier',
            field=models.CharField(blank=True, choices=[('INTQ - Wholesale', 'INTQ - Wholesale'), ('INTQ - OC', 'INTQ - OC'), ('Twilio', 'Twilio')], max_length=16, null=True),
        ),
    ]
