# Generated by Django 5.0.1 on 2024-02-26 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('d221e8db-5b3f-44a9-8bbd-a13f11712a1d'), unique=True),
        ),
    ]
