# Generated by Django 4.2.7 on 2024-02-08 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_dids', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('13df705b-b7d7-4c4c-9e19-d35cf0dd875a'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_dids', to='customers.customer'),
        ),
    ]
