# Generated by Django 5.0.1 on 2024-02-15 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('ebd0732e-eeba-4f8c-9d3d-bae9ff02c371'), unique=True),
        ),
    ]
