# Generated by Django 4.2.7 on 2024-02-06 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Did_Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('reseller', models.CharField(blank=True, max_length=200, null=True)),
                ('in_method', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('change_date', models.CharField(blank=True, max_length=10, null=True)),
                ('voice_carrier', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('sms_enabled', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_carrier', models.CharField(blank=True, max_length=10, null=True)),
                ('sms_type', models.CharField(blank=True, max_length=30, null=True)),
                ('sms_campaign', models.CharField(blank=True, max_length=30, null=True)),
                ('term_location', models.CharField(blank=True, max_length=30, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('extension', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('onboard_date', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('e911_enabled_billed', models.CharField(blank=True, max_length=10, null=True)),
                ('e911_cid', models.CharField(blank=True, null=True)),
                ('e911_address', models.CharField(blank=True, max_length=150, null=True)),
                ('did_uuid', models.CharField(max_length=50, unique=True)),
                ('service_1', models.CharField(blank=True, max_length=100, null=True)),
                ('service_2', models.CharField(blank=True, max_length=100, null=True)),
                ('service_3', models.CharField(blank=True, max_length=100, null=True)),
                ('service_4', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date_time', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('30635add-0064-4e32-a21e-abd557307ab5'), unique=True),
        ),
    ]
