# Generated by Django 4.2.7 on 2024-02-19 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('d5bd23fc-7f50-4e2c-8e66-2548c561a23b'), unique=True),
        ),
    ]
