# Generated by Django 4.2.7 on 2024-02-19 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0002_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('8da548b7-f2c2-4c37-9626-2e85fb30a02e'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
