# Generated by Django 5.0.1 on 2024-01-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0002_alter_did_change_date_alter_did_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='sms_carrier',
            field=models.CharField(blank=True, choices=[('INTQ', 'INTQ'), ('TWL', 'Twilio')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Disco')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='term_location',
            field=models.CharField(blank=True, choices=[('SE', 'SBC - East'), ('SW', 'SBC - West'), ('HE', 'Hosted - East'), ('HW', 'Hosted - West'), ('OC', 'OP - Operator Connect')], max_length=2, null=True),
        ),
    ]
