# Generated by Django 5.0.1 on 2024-02-15 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0002_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('426c9acd-37ca-41f3-a4d4-ca278fa8ecb2'), unique=True),
        ),
    ]
