# Generated by Django 4.2.7 on 2024-02-13 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0002_alter_did_customer_alter_did_did_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('1b837ec4-0055-41ba-85ab-a5b080189cda'), unique=True),
        ),
    ]
