# Generated by Django 4.2.7 on 2024-02-19 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0003_alter_did_did_uuid_alter_did_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('da03d7ac-8162-40b3-9ad4-77529318ab91'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
