# Generated by Django 5.0.1 on 2024-02-29 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0001_initial'),
        ('dids', '0003_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('31f4bfd8-5877-4a75-9f72-7bb8482f1958'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_carrier', to='assist_dids.voice_carrier', to_field='record_id'),
        ),
        migrations.AlterField(
            model_name='did',
            name='voice_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_carrier', to='assist_dids.voice_carrier', to_field='record_id'),
        ),
    ]
