# Generated by Django 4.2.7 on 2024-03-13 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0003_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('95e12cfa-b8c5-4934-a84d-8deda312064e'), unique=True),
        ),
    ]
