# Generated by Django 5.0.1 on 2024-02-29 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0004_alter_did_did_uuid_alter_did_sms_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('42c49fc8-821d-46a3-ab02-7902a4399740'), unique=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='onboard_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='term_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='updated_date_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='voice_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
