# Generated by Django 4.2.7 on 2024-02-13 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0004_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('3dcaf8f1-39ed-499e-9973-a9970efad28b'), unique=True),
        ),
    ]
