# Generated by Django 5.0.1 on 2024-02-20 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0004_alter_did_did_uuid_alter_did_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('e9e4d3b0-0397-4b60-893b-4190c86eeca0'), unique=True),
        ),
    ]
