# Generated by Django 4.2.7 on 2024-03-15 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0004_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('cd23509a-d9fd-4384-b290-46bc1f11d39a'), unique=True),
        ),
    ]
