# Generated by Django 4.2.7 on 2024-03-15 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0005_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('2a4c1f62-6077-4cde-9b80-fbbb104f093a'), unique=True),
        ),
    ]
