# Generated by Django 4.2.7 on 2024-02-13 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0005_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('1a10859d-49f6-4ab4-a4c3-170193726dd3'), unique=True),
        ),
    ]
