# Generated by Django 5.0.1 on 2024-02-29 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0005_alter_did_did_uuid_alter_did_error_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('f72a89dc-a199-4fe1-bd9a-ae47b1952e4b'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='change_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='e911_enabled_billed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_carrier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_enabled',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
