# Generated by Django 4.2.7 on 2024-02-13 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0006_alter_did_did_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='did',
            name='type',
        ),
        migrations.RemoveField(
            model_name='did_error',
            name='type',
        ),
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('3e9c57cf-cbbc-4ff9-be66-186715c9dc86'), unique=True),
        ),
    ]
