# Generated by Django 5.0.1 on 2024-02-29 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0006_alter_did_did_uuid_alter_did_sms_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('e9f3e230-0b12-49b7-99a1-d02c187e76a6'), unique=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='change_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='did_uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='e911_cid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='e911_enabled_billed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='onboard_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_enabled',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='sms_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='term_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did_error',
            name='voice_carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
