# Generated by Django 4.2.7 on 2024-03-26 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0006_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('dc0a809b-3993-4753-a588-afddcb9dc110'), unique=True),
        ),
    ]
