# Generated by Django 5.0.1 on 2024-02-20 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0006_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('48c0a665-9db2-45dc-aba2-fe1638d29acf'), unique=True),
        ),
    ]
