# Generated by Django 4.2.7 on 2024-03-27 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0007_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('ffed82bc-a166-43ef-8034-dbef779321f2'), unique=True),
        ),
    ]
