# Generated by Django 4.2.7 on 2024-02-21 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0007_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('32a22fbb-9363-4338-bd53-89f784ee2268'), unique=True),
        ),
    ]
