# Generated by Django 4.2.7 on 2024-03-27 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0008_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('dd470d4a-3b4f-4e72-89a4-c886d7ecb816'), unique=True),
        ),
    ]
