# Generated by Django 5.0.1 on 2024-02-21 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0008_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('9a5ac684-0f15-41f9-835e-d6929e5410da'), unique=True),
        ),
    ]
