# Generated by Django 4.2.7 on 2024-03-05 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0008_alter_did_did_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('d19876e2-e373-4234-a71c-ee1793070199'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
