# Generated by Django 5.0.1 on 2024-02-21 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0009_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('997390b7-4496-4c36-8af5-461178fe834b'), unique=True),
        ),
    ]
