# Generated by Django 4.2.7 on 2024-03-06 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0009_alter_did_did_uuid_alter_did_sms_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('1d28d966-1d5d-4dd3-ace1-7c0d4939b661'), unique=True),
        ),
    ]
