# Generated by Django 4.2.7 on 2024-03-07 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0010_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('a29a8aff-2948-4817-8761-f33e0e37e9ae'), unique=True),
        ),
    ]
