# Generated by Django 5.0.1 on 2024-02-21 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0010_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='did',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('bb24df17-8d67-4920-95b2-9165c13c6a9c'), unique=True),
        ),
        migrations.AlterField(
            model_name='did',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
