# Generated by Django 5.0.1 on 2024-02-26 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0011_did_is_active_did_is_synced_alter_did_did_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('8f78cf24-5962-4c3a-bfd8-c5addfb790b6'), unique=True),
        ),
    ]
