# Generated by Django 4.2.7 on 2024-03-07 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0011_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('1ca03997-5d16-4c24-8bfb-eaa37bd0cb65'), unique=True),
        ),
    ]
