# Generated by Django 4.2.7 on 2024-03-07 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0012_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('60c23e13-f6b1-492f-be29-ba43034b6ff8'), unique=True),
        ),
    ]
