# Generated by Django 5.0.1 on 2024-02-26 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0012_alter_did_did_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='did_uuid',
            field=models.UUIDField(default=uuid.UUID('9b794fd7-1fe0-4af7-94fd-7440d149f8a0'), unique=True),
        ),
    ]
