# Generated by Django 5.0.1 on 2024-02-26 08:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assist_dids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=50, null=True)),
                ('e911_address', models.CharField(blank=True, max_length=200, null=True)),
                ('e911_city', models.CharField(blank=True, max_length=100, null=True)),
                ('e911_state', models.CharField(blank=True, max_length=20, null=True)),
                ('e911_zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('e911_country', models.CharField(blank=True, max_length=50, null=True)),
                ('support_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('attachments', models.CharField(blank=True, max_length=20, null=True)),
                ('open_balance', models.FloatField(blank=True, null=True)),
                ('record_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_type', to='assist_dids.customer_type', to_field='record_id')),
            ],
        ),
    ]
