# Generated by Django 4.2.7 on 2024-02-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_attachments_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
