# Generated by Django 5.0.1 on 2024-02-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='support_contract',
            new_name='support_contact',
        ),
    ]
