# Generated by Django 5.0.1 on 2024-02-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_support_contract_customer_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='attachments',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
