# Generated by Django 4.2.7 on 2024-02-15 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('number', models.BigIntegerField(unique=True)),
                ('texting', models.TextField(blank=True, null=True)),
                ('requested_port_date', models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y')),
                ('e911_number', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
