# Generated by Django 4.2.7 on 2024-03-08 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('assist_dids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('texting', models.TextField(blank=True, null=True)),
                ('requested_port_date', models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y')),
                ('e911_number', models.BigIntegerField(blank=True, null=True)),
                ('e911_address', models.CharField(blank=True, max_length=255, null=True)),
                ('reseller', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BigIntegerField(default=0)),
                ('sms_enabled', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('sms_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.BigIntegerField(blank=True, null=True)),
                ('onboard_date', models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y')),
                ('e911_enabled_billed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_order', to='customers.customer', to_field='record_id')),
                ('service_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_1', to='assist_dids.service', to_field='record_id')),
                ('service_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_2', to='assist_dids.service', to_field='record_id')),
                ('service_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_3', to='assist_dids.service', to_field='record_id')),
                ('service_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_4', to='assist_dids.service', to_field='record_id')),
                ('service_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.status', to_field='record_id')),
                ('sms_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_carrier_service_order', to='assist_dids.voice_carrier', to_field='record_id')),
                ('sms_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.sms_type', to_field='record_id')),
                ('term_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.term_location', to_field='record_id')),
                ('voice_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_carrier_service_order', to='assist_dids.voice_carrier', to_field='record_id')),
            ],
        ),
    ]
