# Generated by Django 5.0.1 on 2024-02-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='e911_address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='e911_number',
            field=models.BigIntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
