# Generated by Django 4.2.7 on 2024-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='texting',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
