# Generated by Django 4.2.7 on 2024-03-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_Email_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('requested_port_date', models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y')),
            ],
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='requested_port_date',
        ),
        migrations.AddField(
            model_name='service_order',
            name='number_email_dates',
            field=models.ManyToManyField(blank=True, related_name='service_orders', to='service_orders.number_email_date'),
        ),
    ]
