# Generated by Django 5.0.1 on 2024-02-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Deleted'), (1, 'Updated'), (0, 'Created')], default=0),
        ),
    ]
