# Generated by Django 4.2.7 on 2024-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_alter_service_order_texting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='texting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
