# Generated by Django 4.2.7 on 2024-03-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0001_initial'),
        ('service_orders', '0002_number_email_date_remove_service_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_order',
            name='e911_address',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='e911_enabled_billed',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='e911_number',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='onboard_date',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='reseller',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='service_1',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='service_2',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='service_3',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='service_4',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='service_status',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='sms_campaign',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='sms_carrier',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='sms_enabled',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='sms_type',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='user_last_name',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='voice_carrier',
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='e911_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='e911_enabled_billed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='e911_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='extension',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='onboard_date',
            field=models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='reseller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='service_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_1', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='service_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_2', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='service_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_3', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='service_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_4', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='service_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.status', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='sms_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_carrier_service_order', to='assist_dids.voice_carrier', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='sms_enabled',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='sms_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.sms_type', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='number_email_date',
            name='voice_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_carrier_service_order', to='assist_dids.voice_carrier', to_field='record_id'),
        ),
    ]
