# Generated by Django 5.0.1 on 2024-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_service_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'Deleted')], default=0),
        ),
    ]
