# Generated by Django 4.2.7 on 2024-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_alter_service_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
