# Generated by Django 4.2.7 on 2024-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_remove_service_order_e911_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
