# Generated by Django 4.2.7 on 2024-03-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0002_delete_sms_carrier'),
        ('customers', '0001_initial'),
        ('service_orders', '0004_alter_service_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_order', to='customers.customer', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='e911_cid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='e911_enabled_billed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='extension',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='onboard_date',
            field=models.DateField(blank=True, null=True, verbose_name='%m/%d/%Y'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='reseller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='service_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_1', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='service_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_2', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='service_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_3', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='service_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_4', to='assist_dids.service', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='sms_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='sms_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_carrier_service_order', to='assist_dids.voice_carrier', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='sms_enabled',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='sms_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.sms_type', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='term_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.term_location', to_field='record_id'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='voice_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_carrier_service_order', to='assist_dids.voice_carrier', to_field='record_id'),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='e911_address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.status', to_field='record_id'),
        ),
    ]
