# Generated by Django 4.2.7 on 2024-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0004_alter_service_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_email_date',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
