# Generated by Django 4.2.7 on 2024-03-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dids', '0002_delete_sms_carrier'),
        ('service_orders', '0006_remove_service_order_e911_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='service_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_dids.status', to_field='record_id'),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
    ]
