# Generated by Django 4.2.7 on 2024-03-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0006_number_email_date_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number_email_date',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='number_email_date',
            name='user_last_name',
        ),
    ]
