# Generated by Django 4.2.7 on 2024-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0007_remove_number_email_date_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_email_date',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
