/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 140005 (140005)
 Source Host           : localhost:5432
 Source Catalog        : number_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140005 (140005)
 File Encoding         : 65001

 Date: 08/02/2024 00:53:48
*/


-- ----------------------------
-- Table structure for assist_dids_sms_type
-- ----------------------------
DROP TABLE IF EXISTS "public"."assist_dids_sms_type";
CREATE TABLE "public"."assist_dids_sms_type" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(200) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of assist_dids_sms_type
-- ----------------------------
INSERT INTO "public"."assist_dids_sms_type" VALUES (1, '*Point To 18007592727', '*Point To 18007592727');
INSERT INTO "public"."assist_dids_sms_type" VALUES (2, 'Admissions Group', 'Admissions Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (3, 'Advancement Group', 'Advancement Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (4, 'Andosi API', 'Andosi API');
INSERT INTO "public"."assist_dids_sms_type" VALUES (5, 'APi', 'APi');
INSERT INTO "public"."assist_dids_sms_type" VALUES (6, 'Business Office Group', 'Business Office Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (7, 'Carrier Services', 'Carrier Services');
INSERT INTO "public"."assist_dids_sms_type" VALUES (8, 'Clerk SMS', 'Clerk SMS');
INSERT INTO "public"."assist_dids_sms_type" VALUES (9, 'Financial Aid Group', 'Financial Aid Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (10, 'IT Group', 'IT Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (11, 'No', 'No');
INSERT INTO "public"."assist_dids_sms_type" VALUES (12, 'Orphan', 'Orphan');
INSERT INTO "public"."assist_dids_sms_type" VALUES (13, 'Personal', 'Personal');
INSERT INTO "public"."assist_dids_sms_type" VALUES (14, 'Records Office Group', 'Records Office Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (15, 'Residence Life Group', 'Residence Life Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (16, 'SIP Simple', 'SIP Simple');
INSERT INTO "public"."assist_dids_sms_type" VALUES (17, 'Text Enabled NO YAK', 'Text Enabled NO YAK');
INSERT INTO "public"."assist_dids_sms_type" VALUES (18, 'Yak', 'Yak');
INSERT INTO "public"."assist_dids_sms_type" VALUES (19, 'Yak Demo', 'Yak Demo');
INSERT INTO "public"."assist_dids_sms_type" VALUES (20, 'Yak Group', 'Yak Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (21, 'Yak Personal', 'Yak Personal');
INSERT INTO "public"."assist_dids_sms_type" VALUES (22, 'Yak Personal & Group', 'Yak Personal & Group');
INSERT INTO "public"."assist_dids_sms_type" VALUES (23, 'Yak Personal & Shared', 'Yak Personal & Shared');
INSERT INTO "public"."assist_dids_sms_type" VALUES (24, 'Yak Shared', 'Yak Shared');
INSERT INTO "public"."assist_dids_sms_type" VALUES (25, 'Yak Shared Member', 'Yak Shared Member');
INSERT INTO "public"."assist_dids_sms_type" VALUES (26, 'Yakchat', 'Yakchat');
INSERT INTO "public"."assist_dids_sms_type" VALUES (27, 'Yakchat MFA', 'Yakchat MFA');
INSERT INTO "public"."assist_dids_sms_type" VALUES (28, 'Yakchat Personal', 'Yakchat Personal');
INSERT INTO "public"."assist_dids_sms_type" VALUES (29, 'Yes/Personal', 'Yes/Personal');
INSERT INTO "public"."assist_dids_sms_type" VALUES (30, 'Zoom', 'Zoom');

-- ----------------------------
-- Auto increment value for assist_dids_sms_type
-- ----------------------------
SELECT setval('"public"."assist_dids_sms_type_id_seq"', 30, true);

-- ----------------------------
-- Indexes structure for table assist_dids_sms_type
-- ----------------------------
CREATE INDEX "assist_dids_sms_type_name_5855c2f5_like" ON "public"."assist_dids_sms_type" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."varchar_pattern_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table assist_dids_sms_type
-- ----------------------------
ALTER TABLE "public"."assist_dids_sms_type" ADD CONSTRAINT "assist_dids_sms_type_name_key" UNIQUE ("name");

-- ----------------------------
-- Primary Key structure for table assist_dids_sms_type
-- ----------------------------
ALTER TABLE "public"."assist_dids_sms_type" ADD CONSTRAINT "assist_dids_sms_type_pkey" PRIMARY KEY ("id");
