/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 140005 (140005)
 Source Host           : localhost:5432
 Source Catalog        : number_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140005 (140005)
 File Encoding         : 65001

 Date: 08/02/2024 00:54:11
*/


-- ----------------------------
-- Table structure for assist_dids_term_location
-- ----------------------------
DROP TABLE IF EXISTS "public"."assist_dids_term_location";
CREATE TABLE "public"."assist_dids_term_location" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(200) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of assist_dids_term_location
-- ----------------------------
INSERT INTO "public"."assist_dids_term_location" VALUES (1, '7632807349', '7632807349');
INSERT INTO "public"."assist_dids_term_location" VALUES (2, 'Efax', 'Efax');
INSERT INTO "public"."assist_dids_term_location" VALUES (3, 'Hosted - East', 'Hosted - East');
INSERT INTO "public"."assist_dids_term_location" VALUES (4, 'Hosted East', 'Hosted East');
INSERT INTO "public"."assist_dids_term_location" VALUES (5, 'Hosted West', 'Hosted West');
INSERT INTO "public"."assist_dids_term_location" VALUES (6, 'hostedeast', 'hostedeast');
INSERT INTO "public"."assist_dids_term_location" VALUES (7, 'hostedwest', 'hostedwest');
INSERT INTO "public"."assist_dids_term_location" VALUES (8, 'OC', 'OC');
INSERT INTO "public"."assist_dids_term_location" VALUES (9, 'SBC - East', 'SBC - East');
INSERT INTO "public"."assist_dids_term_location" VALUES (10, 'SBC - West', 'SBC - West');
INSERT INTO "public"."assist_dids_term_location" VALUES (11, 'SBC East', 'SBC East');
INSERT INTO "public"."assist_dids_term_location" VALUES (12, 'SBC West', 'SBC West');
INSERT INTO "public"."assist_dids_term_location" VALUES (13, 'Teli EFax', 'Teli EFax');
INSERT INTO "public"."assist_dids_term_location" VALUES (14, 'Yak Dev', 'Yak Devv');
INSERT INTO "public"."assist_dids_term_location" VALUES (15, 'Yak Group', 'Yak Group');

-- ----------------------------
-- Auto increment value for assist_dids_term_location
-- ----------------------------
SELECT setval('"public"."assist_dids_term_location_id_seq"', 15, true);

-- ----------------------------
-- Indexes structure for table assist_dids_term_location
-- ----------------------------
CREATE INDEX "assist_dids_term_location_name_91e6ff52_like" ON "public"."assist_dids_term_location" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."varchar_pattern_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table assist_dids_term_location
-- ----------------------------
ALTER TABLE "public"."assist_dids_term_location" ADD CONSTRAINT "assist_dids_term_location_name_key" UNIQUE ("name");

-- ----------------------------
-- Primary Key structure for table assist_dids_term_location
-- ----------------------------
ALTER TABLE "public"."assist_dids_term_location" ADD CONSTRAINT "assist_dids_term_location_pkey" PRIMARY KEY ("id");
