/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 140005 (140005)
 Source Host           : localhost:5432
 Source Catalog        : number_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140005 (140005)
 File Encoding         : 65001

 Date: 08/02/2024 00:54:02
*/


-- ----------------------------
-- Table structure for assist_dids_status
-- ----------------------------
DROP TABLE IF EXISTS "public"."assist_dids_status";
CREATE TABLE "public"."assist_dids_status" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(200) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of assist_dids_status
-- ----------------------------
INSERT INTO "public"."assist_dids_status" VALUES (3, 'Active', 'Active');
INSERT INTO "public"."assist_dids_status" VALUES (4, 'Active FWD in Teams', 'Active FWD in Teams');
INSERT INTO "public"."assist_dids_status" VALUES (5, 'Active?', 'Active?');
INSERT INTO "public"."assist_dids_status" VALUES (6, 'Carrier Forward', 'Carrier Forward');
INSERT INTO "public"."assist_dids_status" VALUES (7, 'Carrier FWD', 'Carrier FWD');
INSERT INTO "public"."assist_dids_status" VALUES (8, 'Comelit', 'Comelit');
INSERT INTO "public"."assist_dids_status" VALUES (9, 'Disco', 'Disco');
INSERT INTO "public"."assist_dids_status" VALUES (10, 'Disco 2023/11/03', 'Disco 2023/11/03');
INSERT INTO "public"."assist_dids_status" VALUES (11, 'Disco Pending 08/01/23', 'Disco Pending 08/01/23');
INSERT INTO "public"."assist_dids_status" VALUES (12, 'Disco''d', 'Disco''d');
INSERT INTO "public"."assist_dids_status" VALUES (13, 'EFax', 'EFax');
INSERT INTO "public"."assist_dids_status" VALUES (14, 'Fax', 'Fax');
INSERT INTO "public"."assist_dids_status" VALUES (15, 'Fax?', 'Fax?');
INSERT INTO "public"."assist_dids_status" VALUES (16, 'Forward At Carrier', 'Forward At Carrier');
INSERT INTO "public"."assist_dids_status" VALUES (17, 'Forwarded At Carrier', 'Forwarded At Carrier');
INSERT INTO "public"."assist_dids_status" VALUES (18, 'FWD At Carrier', 'FWD At Carrier');
INSERT INTO "public"."assist_dids_status" VALUES (19, 'Hosted', 'Hosted');
INSERT INTO "public"."assist_dids_status" VALUES (20, 'Hosted SMS Only', 'Hosted SMS Only');
INSERT INTO "public"."assist_dids_status" VALUES (21, 'Hosting SMS', 'Hosting SMS');
INSERT INTO "public"."assist_dids_status" VALUES (22, 'INTQ', 'INTQ');
INSERT INTO "public"."assist_dids_status" VALUES (23, 'Inventory', 'Inventory');
INSERT INTO "public"."assist_dids_status" VALUES (24, 'Not Active', 'Not Active');
INSERT INTO "public"."assist_dids_status" VALUES (25, 'Orphan', 'Orphan');
INSERT INTO "public"."assist_dids_status" VALUES (26, 'Parked', 'Parked');
INSERT INTO "public"."assist_dids_status" VALUES (27, 'Pending Disco', 'Pending Disco');
INSERT INTO "public"."assist_dids_status" VALUES (28, 'Port In Rejected', 'Port In Rejected');
INSERT INTO "public"."assist_dids_status" VALUES (29, 'Port Out 09/26/2022', 'Port Out 09/26/2022');
INSERT INTO "public"."assist_dids_status" VALUES (30, 'Port Out Pending FOC', 'Port Out Pending FOC');
INSERT INTO "public"."assist_dids_status" VALUES (31, 'Port Rejected', 'Port Rejected');
INSERT INTO "public"."assist_dids_status" VALUES (32, 'Ported', 'Ported');
INSERT INTO "public"."assist_dids_status" VALUES (33, 'Ported Out', 'Ported Out');
INSERT INTO "public"."assist_dids_status" VALUES (34, 'Ported Out 09092022', 'Ported Out 09092022');
INSERT INTO "public"."assist_dids_status" VALUES (35, 'Ported Out 2023/09/29', 'Ported Out 2023/09/29');
INSERT INTO "public"."assist_dids_status" VALUES (36, 'Porting IN', 'Porting IN');
INSERT INTO "public"."assist_dids_status" VALUES (37, 'SMS Hosting', 'SMS Hosting');
INSERT INTO "public"."assist_dids_status" VALUES (38, 'Snapped Back', 'Snapped Back');
INSERT INTO "public"."assist_dids_status" VALUES (39, 'Spare', 'Spare');
INSERT INTO "public"."assist_dids_status" VALUES (40, 'TN Canceled From Order', 'TN Canceled From Order');
INSERT INTO "public"."assist_dids_status" VALUES (41, 'To Be Disco''d', 'To Be Disco''d');
INSERT INTO "public"."assist_dids_status" VALUES (42, 'To Be Released', 'To Be Released');

-- ----------------------------
-- Auto increment value for assist_dids_status
-- ----------------------------
SELECT setval('"public"."assist_dids_status_id_seq"', 42, true);

-- ----------------------------
-- Indexes structure for table assist_dids_status
-- ----------------------------
CREATE INDEX "assist_dids_status_name_49203b9d_like" ON "public"."assist_dids_status" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."varchar_pattern_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table assist_dids_status
-- ----------------------------
ALTER TABLE "public"."assist_dids_status" ADD CONSTRAINT "assist_dids_status_name_key" UNIQUE ("name");

-- ----------------------------
-- Primary Key structure for table assist_dids_status
-- ----------------------------
ALTER TABLE "public"."assist_dids_status" ADD CONSTRAINT "assist_dids_status_pkey" PRIMARY KEY ("id");
